import {
  AcademyClass,
  Coach,
  MenuItem,
  MembershipPlan,
  Notification,
  StaffMember,
  InventoryItem,
  Transaction,
  TeeTime,
} from "./types";

// Membership & Fees from golf.tcpara.org/membership
export const membershipPlans: MembershipPlan[] = [
  {
    id: "plan-1",
    name: "ParaPro Membership",
    description: "Ol' Colony Golf Unlimited + PARA Tennis + Bowers Park Pool. All-Inclusive PARA.",
    price: 199,
    interval: "monthly",
    features: [
      "Ol' Colony Golf Unlimited",
      "PARA Tennis Membership",
      "All-Inclusive PARA Membership",
      "Bowers Park Pool Summer Membership",
      "$25 one-time registration · $60 annual non-resident fee (waived in Tuscaloosa County)",
      "$25/month per additional family member",
      "Senior (62+): 10% off · Youth (3–15): 10% off · Ages 2 & under: FREE",
    ],
  },
  {
    id: "plan-2",
    name: "Annual Pass — Unlimited",
    description: "Monday–Sunday unlimited play. Month-to-month with yearly contract.",
    price: 1800,
    interval: "annual",
    features: [
      "$25 cart (18 holes) · $15 cart (9 holes)",
      "20% off soft goods · 10% off hard goods",
      "$2 off large range baskets",
      "$40 USGA GHIN handicap service",
      "30-day written notice to cancel",
    ],
  },
  {
    id: "plan-3",
    name: "Annual Pass — Senior (62+)",
    description: "Monday–Friday unlimited play for ages 62 & older.",
    price: 1375,
    interval: "annual",
    features: [
      "Same cart & merchandise discounts as Unlimited",
      "$2 off large range baskets",
      "USGA GHIN handicap service",
      "30-day written notice to cancel",
    ],
  },
  {
    id: "plan-4",
    name: "Annual Pass — Student / Junior",
    description: "Student: $750 per semester. Junior: $750 per year.",
    price: 750,
    interval: "annual",
    features: [
      "Student: $750 per semester",
      "Junior: $750 per year",
      "Full access within plan terms",
      "Cart & merchandise discounts",
    ],
  },
];

export const academyClasses: AcademyClass[] = [
  {
    id: "class-1",
    name: "Little Links (Ages 5-7)",
    description:
      "Introduction to golf fundamentals through fun, age-appropriate activities",
    coach: "Coach Sarah Mitchell",
    coachId: "coach-1",
    ageGroup: "5-7",
    skillLevel: "Beginner",
    schedule: "Saturdays 9:00 AM",
    spotsTotal: 12,
    spotsFilled: 9,
    price: 45,
    location: "Practice Green & Short Course",
  },
  {
    id: "class-2",
    name: "Junior Fundamentals (Ages 8-11)",
    description:
      "Building core skills: grip, stance, swing mechanics, and course etiquette",
    coach: "Coach Marcus Johnson",
    coachId: "coach-2",
    ageGroup: "8-11",
    skillLevel: "Beginner-Intermediate",
    schedule: "Tues/Thurs 4:00 PM",
    spotsTotal: 10,
    spotsFilled: 8,
    price: 65,
    location: "Brion Hardin Teaching Facility",
  },
  {
    id: "class-3",
    name: "Competitive Prep (Ages 12-16)",
    description:
      "Tournament preparation, course strategy, mental game, and advanced techniques",
    coach: "Coach Robert Chen",
    coachId: "coach-3",
    ageGroup: "12-16",
    skillLevel: "Intermediate-Advanced",
    schedule: "Mon/Wed/Fri 3:30 PM",
    spotsTotal: 8,
    spotsFilled: 7,
    price: 95,
    location: "Main Course & Teaching Facility",
  },
  {
    id: "class-4",
    name: "Short Game Mastery",
    description: "Focused training on putting, chipping, and bunker play",
    coach: "Coach Sarah Mitchell",
    coachId: "coach-1",
    ageGroup: "8-16",
    skillLevel: "All Levels",
    schedule: "Wednesdays 5:00 PM",
    spotsTotal: 10,
    spotsFilled: 5,
    price: 55,
    location: "Short Game Area",
  },
  {
    id: "class-5",
    name: "Trackman Junior Lab",
    description:
      "Technology-enhanced instruction using Trackman launch monitor data",
    coach: "Coach Marcus Johnson",
    coachId: "coach-2",
    ageGroup: "10-16",
    skillLevel: "Intermediate+",
    schedule: "Fridays 4:00 PM",
    spotsTotal: 6,
    spotsFilled: 6,
    price: 85,
    location: "Brion Hardin Teaching Facility",
  },
];

export const coaches: Coach[] = [
  {
    id: "coach-1",
    name: "Sarah Mitchell",
    bio: "PGA-certified instructor with 12 years of experience specializing in junior development. Former collegiate golfer at University of Alabama.",
    specialties: ["Junior Development", "Short Game", "Mental Game"],
    certifications: ["PGA Class A", "US Kids Golf Certified", "TPI Level 2"],
    rating: 4.9,
    lessonsGiven: 1842,
    hourlyRate: 85,
    availability: [
      "Mon 9-5",
      "Tue 9-3",
      "Wed 9-5",
      "Thu 9-3",
      "Sat 8-12",
    ],
  },
  {
    id: "coach-2",
    name: "Marcus Johnson",
    bio: "Technology-driven instructor proficient with Trackman, V1 Pro, and Explainer Plane System. 8 years coaching experience.",
    specialties: [
      "Swing Analysis",
      "Trackman Coaching",
      "Full Swing",
      "Club Fitting",
    ],
    certifications: [
      "PGA Class A",
      "Trackman University Level 3",
      "V1 Certified",
    ],
    rating: 4.8,
    lessonsGiven: 1256,
    hourlyRate: 95,
    availability: ["Mon-Fri 10-6", "Sat 9-2"],
  },
  {
    id: "coach-3",
    name: "Robert Chen",
    bio: "Former mini-tour player turned elite junior coach. Specializes in competitive preparation and tournament strategy.",
    specialties: [
      "Tournament Prep",
      "Course Management",
      "Advanced Technique",
      "Mental Performance",
    ],
    certifications: ["PGA Class A", "USGTF Level IV", "Mental Game Coaching"],
    rating: 4.95,
    lessonsGiven: 978,
    hourlyRate: 110,
    availability: ["Mon-Fri 2-7", "Sat 8-1"],
  },
  {
    id: "coach-4",
    name: "Lisa Park",
    bio: "Specializes in beginner adult and family group lessons. Passionate about growing the game for all ages.",
    specialties: [
      "Beginner Instruction",
      "Group Lessons",
      "Family Programs",
      "Women's Golf",
    ],
    certifications: ["PGA Associate", "LPGA Teaching Certified"],
    rating: 4.85,
    lessonsGiven: 645,
    hourlyRate: 75,
    availability: ["Tue-Sat 9-5"],
  },
];

export const menuItems: MenuItem[] = [
  {
    id: "menu-1",
    name: "Colony Club Sandwich",
    description:
      "Grilled chicken, bacon, lettuce, tomato, and honey mustard on toasted sourdough",
    price: 12.99,
    category: "sandwich",
    available: true,
    popular: true,
  },
  {
    id: "menu-2",
    name: "Birdie Burger",
    description:
      "1/3 lb Angus patty, cheddar, pickles, onions, and colony sauce",
    price: 11.99,
    category: "entree",
    available: true,
    popular: true,
  },
  {
    id: "menu-3",
    name: "Eagle Wings",
    description: "Crispy bone-in wings tossed in your choice of sauce (8 pc)",
    price: 10.99,
    category: "appetizer",
    available: true,
  },
  {
    id: "menu-4",
    name: "19th Hole Nachos",
    description: "Loaded nachos with queso, jalapeños, pico de gallo, and sour cream",
    price: 9.99,
    category: "appetizer",
    available: true,
    popular: true,
  },
  {
    id: "menu-5",
    name: "Fairway Caesar Salad",
    description: "Romaine, parmesan, croutons, and classic caesar dressing",
    price: 8.99,
    category: "entree",
    available: true,
  },
  {
    id: "menu-6",
    name: "The Mulligan Dog",
    description: "All-beef hot dog with your choice of toppings",
    price: 6.99,
    category: "entree",
    available: true,
  },
  {
    id: "menu-7",
    name: "Draft Beer",
    description: "Rotating selection of local and national craft beers",
    price: 5.99,
    category: "beverage",
    available: true,
  },
  {
    id: "menu-8",
    name: "Sweet Tea",
    description: "Southern-style sweet or unsweet tea",
    price: 2.99,
    category: "beverage",
    available: true,
  },
  {
    id: "menu-9",
    name: "Brownie Sundae",
    description: "Warm chocolate brownie with vanilla ice cream and caramel drizzle",
    price: 7.99,
    category: "dessert",
    available: true,
  },
];

export const notifications: Notification[] = [
  {
    id: "notif-1",
    title: "Tee Time Reminder",
    message:
      "Your tee time is tomorrow at 8:30 AM. Check in at the Pro Shop 15 minutes early.",
    type: "info",
    read: false,
    createdAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "notif-2",
    title: "Payment Successful",
    message: "Your monthly membership payment of $89.00 has been processed.",
    type: "success",
    read: false,
    createdAt: "2026-03-01T08:00:00Z",
  },
  {
    id: "notif-3",
    title: "Class Schedule Update",
    message:
      'Junior Fundamentals class on Thursday has been moved to 4:30 PM due to weather.',
    type: "warning",
    read: true,
    createdAt: "2026-02-28T14:00:00Z",
  },
  {
    id: "notif-4",
    title: "New Tournament Registration Open",
    message:
      "Spring Junior Championship registration is now open. Limited to 32 players.",
    type: "info",
    read: true,
    createdAt: "2026-02-27T09:00:00Z",
  },
  {
    id: "notif-5",
    title: "Renewal Reminder",
    message:
      "Your annual membership renews on April 1, 2026. Update payment info if needed.",
    type: "billing",
    read: false,
    createdAt: "2026-02-26T12:00:00Z",
  },
];

export const staffMembers: StaffMember[] = [
  { id: "staff-1", name: "James Wilson", role: "Pro Shop Associate", division: "pro_shop", shift: "7 AM - 3 PM", status: "active" },
  { id: "staff-2", name: "Emily Rodriguez", role: "Pro Shop Manager", division: "pro_shop", shift: "8 AM - 4 PM", status: "active" },
  { id: "staff-3", name: "David Thompson", role: "Range Attendant", division: "driving_range", shift: "6 AM - 2 PM", status: "active" },
  { id: "staff-4", name: "Ashley Brown", role: "Grill Cook", division: "grill", shift: "10 AM - 6 PM", status: "active" },
  { id: "staff-5", name: "Michael Lee", role: "Grill Server", division: "grill", shift: "11 AM - 7 PM", status: "active" },
  { id: "staff-6", name: "Chris Martinez", role: "Greenskeeper", division: "greens", shift: "5 AM - 1 PM", status: "active" },
  { id: "staff-7", name: "Tom Harris", role: "Superintendent", division: "greens", shift: "5 AM - 1 PM", status: "active" },
  { id: "staff-8", name: "Kara Williams", role: "Starter/Marshal", division: "operations", shift: "7 AM - 3 PM", status: "off-duty" },
];

export const inventory: InventoryItem[] = [
  { id: "inv-1", name: "Titleist Pro V1 (Dozen)", category: "Golf Balls", quantity: 45, reorderLevel: 20, price: 54.99, division: "pro_shop" },
  { id: "inv-2", name: "Callaway Rogue Driver", category: "Clubs", quantity: 8, reorderLevel: 3, price: 499.99, division: "pro_shop" },
  { id: "inv-3", name: "Ol' Colony Logo Polo", category: "Apparel", quantity: 32, reorderLevel: 10, price: 45.00, division: "pro_shop" },
  { id: "inv-4", name: "Range Ball Bucket (100)", category: "Range Supplies", quantity: 180, reorderLevel: 50, price: 12.00, division: "driving_range" },
  { id: "inv-5", name: "Gloves (Medium)", category: "Accessories", quantity: 15, reorderLevel: 8, price: 18.99, division: "pro_shop" },
  { id: "inv-6", name: "Angus Patties (Case)", category: "Food", quantity: 12, reorderLevel: 5, price: 89.00, division: "grill" },
  { id: "inv-7", name: "Chicken Breast (Case)", category: "Food", quantity: 8, reorderLevel: 4, price: 64.00, division: "grill" },
  { id: "inv-8", name: "Draft Beer Keg", category: "Beverage", quantity: 4, reorderLevel: 2, price: 165.00, division: "grill" },
];

export const transactions: Transaction[] = [
  { id: "txn-1", date: "2026-03-01", description: "Monthly Membership - Johnson Family", amount: 149.00, type: "payment", status: "completed", division: "operations" },
  { id: "txn-2", date: "2026-03-01", description: "Private Lesson - Coach Sarah Mitchell", amount: 85.00, type: "payment", status: "completed", division: "academy" },
  { id: "txn-3", date: "2026-03-01", description: "Commission - Sarah Mitchell (15%)", amount: -12.75, type: "commission", status: "completed", division: "academy" },
  { id: "txn-4", date: "2026-02-28", description: "Pro V1 Golf Balls (2 Dozen)", amount: 109.98, type: "payment", status: "completed", division: "pro_shop" },
  { id: "txn-5", date: "2026-02-28", description: "Grill Orders - Daily Total", amount: 487.50, type: "payment", status: "completed", division: "grill" },
  { id: "txn-6", date: "2026-02-28", description: "Junior Academy - Spring Registration (x5)", amount: 645.00, type: "payment", status: "completed", division: "academy" },
  { id: "txn-7", date: "2026-02-27", description: "Range Tokens (50)", amount: 250.00, type: "payment", status: "completed", division: "driving_range" },
  { id: "txn-8", date: "2026-02-27", description: "Refund - Cancelled Lesson", amount: -95.00, type: "refund", status: "completed", division: "academy" },
];

export const teeTimes: TeeTime[] = [
  { id: "tt-1", date: "2026-03-02", time: "7:00 AM", players: 4, maxPlayers: 4, status: "booked", bookedBy: "Johnson Party" },
  { id: "tt-2", date: "2026-03-02", time: "7:12 AM", players: 2, maxPlayers: 4, status: "booked", bookedBy: "Smith/Chen" },
  { id: "tt-3", date: "2026-03-02", time: "7:24 AM", players: 0, maxPlayers: 4, status: "available" },
  { id: "tt-4", date: "2026-03-02", time: "7:36 AM", players: 0, maxPlayers: 4, status: "available" },
  { id: "tt-5", date: "2026-03-02", time: "7:48 AM", players: 3, maxPlayers: 4, status: "booked", bookedBy: "Williams Group" },
  { id: "tt-6", date: "2026-03-02", time: "8:00 AM", players: 0, maxPlayers: 4, status: "available" },
  { id: "tt-7", date: "2026-03-02", time: "8:12 AM", players: 4, maxPlayers: 4, status: "booked", bookedBy: "Corporate Outing" },
  { id: "tt-8", date: "2026-03-02", time: "8:24 AM", players: 0, maxPlayers: 4, status: "available" },
  { id: "tt-9", date: "2026-03-02", time: "8:36 AM", players: 0, maxPlayers: 4, status: "blocked" },
  { id: "tt-10", date: "2026-03-02", time: "8:48 AM", players: 1, maxPlayers: 4, status: "booked", bookedBy: "Walk-in" },
];

export const analyticsData = {
  enrollmentTrend: [
    { month: "Oct", students: 42 },
    { month: "Nov", students: 48 },
    { month: "Dec", students: 35 },
    { month: "Jan", students: 52 },
    { month: "Feb", students: 61 },
    { month: "Mar", students: 68 },
  ],
  revenueByDivision: [
    { name: "Academy", value: 24500, fill: "#16a34a" },
    { name: "Pro Shop", value: 18200, fill: "#15803d" },
    { name: "Grill", value: 12800, fill: "#c9a84c" },
    { name: "Memberships", value: 31000, fill: "#166534" },
    { name: "Driving Range", value: 8400, fill: "#86efac" },
  ],
  monthlyRevenue: [
    { month: "Oct", revenue: 82000, expenses: 61000 },
    { month: "Nov", revenue: 78000, expenses: 58000 },
    { month: "Dec", revenue: 65000, expenses: 55000 },
    { month: "Jan", revenue: 88000, expenses: 62000 },
    { month: "Feb", revenue: 94000, expenses: 64000 },
    { month: "Mar", revenue: 102000, expenses: 66000 },
  ],
  classAttendance: [
    { name: "Little Links", attendance: 92, capacity: 100 },
    { name: "Jr. Fundamentals", attendance: 85, capacity: 100 },
    { name: "Competitive Prep", attendance: 96, capacity: 100 },
    { name: "Short Game", attendance: 72, capacity: 100 },
    { name: "Trackman Lab", attendance: 100, capacity: 100 },
  ],
  membershipBreakdown: [
    { name: "Individual Monthly", count: 124 },
    { name: "Individual Annual", count: 86 },
    { name: "Family Monthly", count: 45 },
    { name: "Junior Academy", count: 68 },
  ],
  peakHours: [
    { hour: "6 AM", bookings: 4 },
    { hour: "7 AM", bookings: 12 },
    { hour: "8 AM", bookings: 18 },
    { hour: "9 AM", bookings: 22 },
    { hour: "10 AM", bookings: 20 },
    { hour: "11 AM", bookings: 16 },
    { hour: "12 PM", bookings: 14 },
    { hour: "1 PM", bookings: 18 },
    { hour: "2 PM", bookings: 20 },
    { hour: "3 PM", bookings: 16 },
    { hour: "4 PM", bookings: 12 },
    { hour: "5 PM", bookings: 8 },
    { hour: "6 PM", bookings: 4 },
  ],
};
